string frame_name
geometry_msgs/Pose move_to_pose
geometry_msgs/Vector3 translation
geometry_msgs/Quaternion rotation
bool exec_wait_for_user_input
bool execute
---
bool success
string[] joint_names
float32[] joint_values
